import type { WatchdogRule } from "@commerce-watchdog/shared";

export const BUILT_IN_RULES: WatchdogRule[] = [
  {
    ruleCode: "PAYMENT_FAILED_NO_RETRY",
    name: "Payment Failed — No Retry",
    description: "Payment gateway returned a failure and the user did not attempt again within 15 minutes.",
    severity: "critical",
    triggerStages: ["PAYMENT_INITIATED"],
    condition: "payment_failed && no_retry_within_15m",
    recommendedAction: "Trigger automated retry email. Offer alternative payment method. Check gateway logs.",
    autoRetryPossible: true,
  },
  {
    ruleCode: "CHECKOUT_ABANDONED_AFTER_ADDRESS",
    name: "Checkout Abandoned After Address",
    description: "User submitted address but did not reach payment screen within 20 minutes.",
    severity: "high",
    triggerStages: ["ADDRESS_SUBMITTED"],
    condition: "no_payment_initiated_within_20m",
    recommendedAction: "Send abandoned checkout recovery email/SMS with direct payment link.",
    autoRetryPossible: false,
  },
  {
    ruleCode: "CART_ABANDONED_HIGH_VALUE",
    name: "High-Value Cart Abandoned",
    description: "Cart value > ₹5000 and user has not started checkout within 30 minutes of viewing cart.",
    severity: "high",
    triggerStages: ["CART_VIEWED"],
    condition: "cart_value_gt_5000 && no_checkout_started_within_30m",
    recommendedAction: "Send personalised recovery message. Consider one-time coupon.",
    autoRetryPossible: false,
  },
  {
    ruleCode: "ORDER_CREATED_NO_CONFIRMATION",
    name: "Order Created — No Confirmation Received",
    description: "Order was created in backend but ORDER_CONFIRMED event never fired within 5 minutes.",
    severity: "critical",
    triggerStages: ["ORDER_CREATED"],
    condition: "no_order_confirmed_within_5m",
    recommendedAction: "Check payment webhook delivery. Verify order status in admin. Contact customer proactively.",
    autoRetryPossible: false,
  },
  {
    ruleCode: "INVOICE_NOT_GENERATED",
    name: "Invoice Not Generated",
    description: "ORDER_CONFIRMED stage passed but INVOICE_GENERATED event was not received within 10 minutes.",
    severity: "medium",
    triggerStages: ["ORDER_CONFIRMED"],
    condition: "no_invoice_generated_within_10m",
    recommendedAction: "Check invoice generation service. Manually trigger invoice. Notify customer of delay.",
    autoRetryPossible: true,
  },
  {
    ruleCode: "ORDER_HISTORY_MISSING",
    name: "Order Not Visible in History",
    description: "Order confirmed but ORDER_HISTORY_VISIBLE event not received — buyer cannot see their order.",
    severity: "high",
    triggerStages: ["ORDER_CONFIRMED"],
    condition: "no_order_history_visible_within_15m",
    recommendedAction: "Check order sync job. Verify database write succeeded. Clear buyer session cache.",
    autoRetryPossible: true,
  },
  {
    ruleCode: "PAYMENT_SUCCESS_ORDER_NOT_CREATED",
    name: "Payment Succeeded — Order Not Created",
    description: "PAYMENT_SUCCESS event received but ORDER_CREATED never followed within 5 minutes.",
    severity: "critical",
    triggerStages: ["PAYMENT_SUCCESS"],
    condition: "no_order_created_within_5m",
    recommendedAction: "URGENT: Payment collected but no order. Check order creation API logs. Manually create order and contact customer immediately.",
    autoRetryPossible: false,
  },
  {
    ruleCode: "SHIPPING_CALCULATION_FAILED",
    name: "Shipping Calculation Failed or Slow",
    description: "Shipping calculation took more than 8 seconds or returned an error.",
    severity: "medium",
    triggerStages: ["SHIPPING_CALCULATED"],
    condition: "api_latency_gt_8000 || api_status_gte_400",
    recommendedAction: "Check shipping service provider API. Consider caching shipping rates. Offer manual shipping options.",
    autoRetryPossible: true,
  },
  {
    ruleCode: "REPEAT_PAYMENT_FAILURES",
    name: "Repeated Payment Failures — Same Session",
    description: "Three or more PAYMENT_INITIATED events with failure in a single session.",
    severity: "high",
    triggerStages: ["PAYMENT_INITIATED"],
    condition: "payment_failure_count_gte_3_in_session",
    recommendedAction: "Contact buyer directly. Offer bank transfer / offline payment option. Check if card/UPI details are flagged.",
    autoRetryPossible: false,
  },
  {
    ruleCode: "API_ERROR_SPIKE",
    name: "API Error Spike",
    description: "More than 10 API errors (status 5xx) in any 5-minute rolling window across all sessions.",
    severity: "critical",
    triggerStages: ["CHECKOUT_STARTED", "PAYMENT_INITIATED", "ORDER_CREATED"],
    condition: "api_5xx_count_gt_10_in_5m_window",
    recommendedAction: "Check backend server health. Review recent deployments. Enable maintenance mode if necessary.",
    autoRetryPossible: false,
  },
];
